add section about using the `UNSAFE_CAST` function to silence errors
hhvm/user-documentation pull request #1046
Opened 2021-06-25 13:54 UTC by enetsee

Added an example of using the `UNSAFE_CAST` function to silence errors and highlighted the key difference and similarities to using `HH_FIXME` comments, specifically:
-  only applies to expressions with errors arising from a type mistmatch
- does change the type of the expression in subsequent typechecking
-  _must_ be applied to each sub-expression with a type mismatch 
- has no runtime impact

2021-06-25 14:02 UTC, lexidor commented
I believe mistmatch may have been a typo. Line 130.

2021-06-25 14:07 UTC, lexidor commented
Something worth noting. Adding a suppression comment above an assignment statement makes the assigned variable assume the type `_`. This means that you inadvertently disable all checks for all uses of this variable. Unsafe cast does not suffer from this fate.

2021-06-25 14:15 UTC, enetsee commented
Interesting; I just tried this (so I could tell you which of `Tany` and `Terr` we see) but I still see the return type of `takes_int` (i.e. `int`) in this example:

```
function takes_int(int $i): int {
  return $i;
}

function takes_float(float $i): float {
  /* HH_FIXME[4110] */
  $x = takes_int($i);
  return $x;
}
```

2021-06-25 14:33 UTC, lexidor commented
```HACK
function json_decode_mixed(string $_json): mixed {
  return dict['hello' => 'world'];
}

function main(): void {
  $x = json_decode_mixed('{"hello": "world"}');
  /*HH_FIXME[4110]*/
  foreach ($x as $hello => $world) {
    takes_float($hello);
    takes_float($world);
  }
}

function takes_float(float $_): void {}
```
Here is an example where UNSAFE_CAST would be helpful. You could UNSAFE_CAST to a Traversable<string, string> (which is not enforceable). This would give types to `$hello` and `$world`.

2021-06-25 14:37 UTC, lexidor commented
> Interesting; I just tried this (so I could tell you which of `Tany` and `Terr` we see) but I still see the return type of `takes_int` (i.e. `int`) in this example:
> 
> ```
> function takes_int(int $i): int {
>   return $i;
> }
> 
> function takes_float(float $i): float {
>   /* HH_FIXME[4110] */
>   $x = takes_int($i);
>   return $x;
> }
> ```

Thanks for teaching me something about suppression comments. I thought Hack, always gave up on inferring a local variable if an error was suppressed. Good to know that Hack will still try.

2021-06-25 14:38 UTC, enetsee commented
Got it; so, in the foreach, `$x` get's treated as a `KeyedTraversable<nothing,nothing>` and both `$hello` and `$world` are, consequently, `nothing` in the calls to `takes_float`.

2021-06-25 14:47 UTC, lexidor commented
Yep, iterating over an error results in `nothing`. `nothing` can flow anywhere. I am again surprised by the inference. Previous versions inferred the even more unsound `TErr`. Simple subscripting still does infer `TErr`.

```HACK
function json_decode_mixed(string $_json): mixed {
  return dict['hello' => 'world'];
}

function main(): void {
  $x = json_decode_mixed('{"hello": "world"}');
  /*HH_FIXME[4063]*/
  $y = $x['hello'];
  takes_float($y);
}

function takes_float(float $_): void {}
```

2021-06-25 15:08 UTC, enetsee commented
That's a lovely example; because array indexing on nullable containers is a common pattern, it get's special cased. The problem is, we haven't really got a sensible type to suggest in general (without complement or subtraction across all types). The upshot is, `Hole`s aren't generated during typing at the moment but we could worst-case it to `nothing` - thanks for sharing!

2021-06-28 17:37 UTC, fredemmott requested changes
Thanks so much, just a few small things about structure :)

2021-06-28 17:37 UTC, fredemmott commented on guides/hack/30-silencing-errors/01-introduction.md
> +```
Can you change this to:

~~~
```silencing_errors_per_expression.hack
~~~

... then re-run build.php? That should auto-generate a .ex[pect file, and if anything changes in Hack that makes the behavior of this example change, we'll automatically find out.

2021-06-28 17:37 UTC, fredemmott commented on guides/hack/30-silencing-errors/01-introduction.md
> +### Silencing Errors per Expression
Can you move this above the 'with comments' part?

While it's a less general approach, people will often stop reading when they find the first thing that works, so we should make it so they see this first.

2021-06-30 19:48 UTC, fredemmott approved these changes

2021-07-07 22:15 UTC, merged