Added an example for the HH\Lib\Math\sqrt function
hhvm/user-documentation pull request #1305
Opened 2022-10-20 10:14 UTC by JamesHagertyMeta

For task [T133748369](https://www.internalfb.com/intern/tasks/?t=133748369)

2022-10-20 21:23 UTC, kunalb6 commented
pls add a screenshot of the example

2022-10-21 19:52 UTC, JamesHagertyMeta commented
> pls add a screenshot of the example

Hello, so when I opened up an instance copy of the documentation, the page did not change (did not show the example I wrote). Are there other files to be edited to make it show up?

2022-10-21 20:41 UTC, Atry requested changes
@JamesHagertyMeta, are you using GitHub Codespace for development? Could you fix the test failure then try again?

2026-01-10 06:59 UTC, tlil commented
Closing as this is obsolete with the new, Docusaurus-migrated doc site: https://docs.hhvm.com/docs/apis/overview/

<img width="1015" height="228" alt="image" src="https://github.com/user-attachments/assets/efed78ab-3839-4537-8cfd-a1bca60c6d91" />

2026-01-10 06:59 UTC, closed without merging